url:      https://i1oy.github.io
title:    Personal BLOG
subtitle: i1oy's blog.
author:   i1oy

markdown: kramdown

# theme:    jekyll-theme-cayman
theme:    jekyll-theme-tactile

plugins:
  - "jekyll-github-metadata"
